services: #Defining all the containiners  - we need postgres and pgadmin
  pgdb:    #Name of the service - identifier - can be named anything 
    image: postgres:latest    #name of the docker image, latest version eg. python:3.12
    environment: #Default env variables
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=hotel_bookings
    ports:
      - "5432:5432" #port to port mapping
    volumes: #/var/lib is a linux dir system for variable long term data storage - volumes is used for persistent data storage independent of active containers
      - ./hotel-bookings-data/db_data:/var/lib/postgresql/data:rw   #Mounts the data in the postgres_data dir to var/lib/../data - rw-read/write

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"

